# Generated by Django 4.1.2 on 2022-10-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_ems_tehsil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ems_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdeleted', models.BooleanField()),
            ],
        ),
    ]
