# Generated by Django 4.1.2 on 2022-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_ems_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ems_country',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
