# Generated by Django 4.1.2 on 2022-10-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_ems_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ems_constituency',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='ems_country',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='ems_district',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='ems_province',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='ems_tehsil',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='ems_type',
            name='isdeleted',
        ),
    ]
