# Generated by Django 4.1.2 on 2022-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_ems_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ems_tehsil',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
