# Generated by Django 4.1.2 on 2022-10-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_ems_tehsil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ems_type',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
